### ISSUE TITLE
npm install fails to build exokit on aarch64

### ISSUE THREAD

**Issue by rizend** [webmixedreality/exokit#786] opened 2019-02-26 09:52 UTC
# Platform

* CPU Architecture: ARM aarch64 Little Endian (tested on a [ROCK64 from Pine64](https://www.pine64.org/?product=rock64-media-board-computer) and an arm server from [Scaleway](https://www.scaleway.com/))
* OS: Ubuntu Bionic

# Steps To Reproduce

1. `git clone https://github.com/webmixedreality/exokit`
2. Download node (`https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-arm64.tar.xz`), extract archive, and add bin folder to path.
3. `cd exokit` and `npm install`

# Expected Result

`npm install` builds exokit without errors.

# Actual Result

`npm install` produces multiple errors:

```
tar (child): /home/r/exokit/node_modules/native-browser-deps-linux/lib4.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: invalid status code 2
    at ChildProcess.cp.on.code (/home/r/exokit/node_modules/native-browser-deps-linux/postinstall.js:84:15)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
make: Entering directory '/home/r/exokit/build'
  CXX(target) Release/obj.target/exokit/exokit.o
In file included from ../exokit.cpp:10:0:
/home/r/exokit/deps/exokit-bindings/bindings/include/bindings.h:16:10: fatal error: browser.h: No such file or directory
 #include <browser.h>
          ^~~~~~~~~~~
compilation terminated.
exokit.target.mk:208: recipe for target 'Release/obj.target/exokit/exokit.o' failed
make: *** [Release/obj.target/exokit/exokit.o] Error 1
make: Leaving directory '/home/r/exokit/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/r/node-v10.15.1-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.93-mainline-rev1
gyp ERR! command "/home/r/node-v10.15.1-linux-arm64/bin/node" "/home/r/node-v10.15.1-linux-arm64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/r/exokit
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exokit@0.0.517 install: `node ./scripts/preinstall.js && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the exokit@0.0.517 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/r/.npm/_logs/2019-02-26T09_12_21_426Z-debug.log
```

[Full NPM build log](https://gist.github.com/rizend/fe1d260f986415ab8ceb021d0e07bef0)

# Notes on the first error

Looking in the `node_modules/native-browser-deps-linux`, it appears that the first error (beginning `tar (child):`) is caused by trying to extract the `lib4.xz` file multiple times.  I tried checking whether the archive had already been extracted, but I still get the error from node-gyp (beginning `In file included from ../exokit.cpp:10:0:`).

**Comment by modulesio** [comment] 2019-02-27 15:06
AARCH64 is only supported on Magic Leap right now, and hopefully soon other Android derivatives like Oculus Go/actual android. Linux itself however is not on that roadmap.

Although I expect it wouldn't be too bad to port to Linux, because most of the libraries are not OS-specific, there are places you'd probably run into trouble, such as libcef integration which cares more about the underlying platform.

We'd take a pull request to add this support, however. The fix for the particular error about is to do a linkage port for libcef ARM64/Linux. That might be enough for the rest to go smoothly, but I haven't tried enough to know for sure.

**Comment by modulesio** [comment] 2019-03-01 20:46
Closing this for now as working as intended; if we want to work on Ubuntu ARM64, we should make an implementation issue + PR for it.

**Closed by modulesio** 2019-03-01 20:46 UTC
