### ISSUE TITLE
ML: audio context does not survive destroy

### ISSUE THREAD

**Issue by machenmusik** [webmixedreality/exokit#537] opened 2018-10-16 14:17 UTC
https://speech-polyfill.azurewebsites.net/

While verifying #484 using #477,
some debugging indicates that things are working until recognition.stop() is called,
which tries to destroy the audio context, as a new one will be created upon recognition.start()

On ML (did not test others), recognition.stop() does not successfully return, and thus recognition becomes and remains broken.

**Comment by machenmusik** [comment] 2018-10-19 14:28
from Slack a while back:


looks like recognition.stop() doesn't come back

machenmusik [9:44 AM]
... looks like that destroys audio context https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/src/common.browser/MicAudioSource.ts#L159
src/common.browser/MicAudioSource.ts:159
    ```public TurnOff = (): Promise<boolean> => {```
Azure-Samples/SpeechToText-WebSockets-JavascriptAdded by GitHub
and then a new one is created when recognition is restarted https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/src/common.browser/MicAudioSource.ts#L55
src/common.browser/MicAudioSource.ts:55
    ```public TurnOn = (): Promise<boolean> => {```
Azure-Samples/SpeechToText-WebSockets-JavascriptAdded by GitHub
... and exokit doesn't survive the TurnOff attempt

**Comment by machenmusik** [comment] 2018-10-26 15:09
0.0.494 still has the issue.

**Comment by modulesio** [comment] 2018-10-26 15:44
Whoops thanks, didn’t mean to close this yet.

**Comment by modulesio** [comment] 2018-10-27 00:48
Added the speech demo link to the OP.

**Comment by modulesio** [comment] 2018-10-27 07:56
Writing down for posterity:

The main hang we have now is that the audio context destruction does not return.

After analysis this is the result of context destruction is:

- waiting for the context to finish rendering requires joining the Labsound audio graph thread
- the audio graph thread has a tail time to account for flushing existing buffers, and waits for enough sample time to pass through the render thread
- time only passes in the render thread while rendering happens
- if there is a `ScriptProcessorNode` in the render chain, that requires calling back to the main thread to execute the user logic
- we cannot call back to the main thread because the main thread is waiting for the context to finish rendering in the first place
 - this is a deadlock

Seems the right solution would be to make the tail unwind asynchronous.

**Comment by modulesio** [comment] 2018-10-27 09:29
Closing this one as a dupe of https://github.com/webmixedreality/exokit/issues/477, since this is understood as no longer an issue of AudioContext destruction (for which we have a working example), but the specific circumstances in the polyfill.

**Closed by modulesio** 2018-10-27 09:29 UTC
Labels: bug
