### ISSUE TITLE
crash on booting a-painter in exokit.cmd

### ISSUE THREAD

**Issue by ChrisEddy** [webmixedreality/exokit#451] opened 2018-09-10 06:58 UTC
Running the command: ` ./exokit.cmd https://aframe.io/a-painter`

My OS is windows 10
Exokit version 0.0.459

The window comes up for 1 second and then goes non-responsive and requires a hard-exit from windows to unlock the crash.

I get this error:

```
Caught crash 13f24d1b c0000374
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (934): StackWalker::ShowCallstack
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\segfault-handler.cpp (227): segfault_handler
00007FF813E95678 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FF813E3692A (ntdll): (filename not available): RtlWalkFrameChain
00007FF813E352CA (ntdll): (filename not available): RtlRaiseException
00007FF813F24D1B (ntdll): (filename not available): RtlIsNonEmptyDirectoryReparsePointAllowed
00007FF813F2C7E6 (ntdll): (filename not available): RtlpNtSetValueKey
00007FF813F2CAB1 (ntdll): (filename not available): RtlpNtSetValueKey
00007FF813EC9A15 (ntdll): (filename not available): RtlRaiseStatus
00007FF813F2C70B (ntdll): (filename not available): RtlpNtSetValueKey
00007FF813ED5FA9 (ntdll): (filename not available): memset
00007FF813E53547 (ntdll): (filename not available): RtlProtectHeap
00007FF813E46117 (ntdll): (filename not available): RtlSizeHeap
00007FF813E42B55 (ntdll): (filename not available): RtlAllocateHeap
minkernel\crts\ucrt\src\appcrt\heap\malloc_base.cpp (34): _malloc_base
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (624): StackWalkerInternal::LoadModule
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (875): StackWalker::LoadModules
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (901): StackWalker::ShowCallstack
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\segfault-handler.cpp (227): segfault_handler
00007FF813E95678 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FF813E3692A (ntdll): (filename not available): RtlWalkFrameChain
00007FF813ECDC1E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FF813E45A78 (ntdll): (filename not available): RtlSizeHeap
00007FF813E42B55 (ntdll): (filename not available): RtlAllocateHeap
minkernel\crts\ucrt\src\appcrt\heap\malloc_base.cpp (34): _malloc_base
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (624): StackWalkerInternal::LoadModule
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (875): StackWalker::LoadModules
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (901): StackWalker::ShowCallstack
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\segfault-handler.cpp (227): segfault_handler
00007FF813E95678 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FF813E3692A (ntdll): (filename not available): RtlWalkFrameChain
00007FF813ECDC1E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FF813E45A78 (ntdll): (filename not available): RtlSizeHeap
00007FF813E42B55 (ntdll): (filename not available): RtlAllocateHeap
00007FF8111CA506 (ucrtbase): (filename not available): malloc_base
00007FF8111CD6EA (ucrtbase): (filename not available): o_malloc
00007FF807058E6B (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070F212D (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070F2FE8 (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070F2DE2 (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070F37D1 (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070F207F (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070F0F75 (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070E5DFB (dbghelp): (filename not available): SymSetSearchPathW
00007FF8070E712F (dbghelp): (filename not available): SymSetSearchPathW
00007FF80705A7CD (dbghelp): (filename not available): SymSetSearchPathW
00007FF80705A62D (dbghelp): (filename not available): SymSetSearchPathW
00007FF80712DC39 (dbghelp): (filename not available): SymSetSearchPathW
00007FF807137E95 (dbghelp): (filename not available): SymSetSearchPathW
00007FF807134D6F (dbghelp): (filename not available): SymSetSearchPathW
00007FF807153237 (dbghelp): (filename not available): SymFindFileInPathW
00007FF8071562B9 (dbghelp): (filename not available): SymFindFileInPathW
00007FF807153A63 (dbghelp): (filename not available): SymFindFileInPathW
00007FF80714ED90 (dbghelp): (filename not available): SymLoadModuleEx
00007FF80714ECF6 (dbghelp): (filename not available): SymLoadModule64
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (610): StackWalkerInternal::LoadModule
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (875): StackWalker::LoadModules
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\stackwalker.cpp (901): StackWalker::ShowCallstack
c:\users\ceddy\downloads\exokit-master\exokit-master\node_modules\fault-zone\src\segfault-handler.cpp (227): segfault_handler
00007FF813E95678 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FF813E3692A (ntdll): (filename not available): RtlWalkFrameChain
00007FF813ECDC1E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FF813E45A78 (ntdll): (filename not available): RtlSizeHeap
00007FF813E42B55 (ntdll): (filename not available): RtlAllocateHeap
00007FF813E493B9 (ntdll): (filename not available): RtlLockHeap
00007FF813E495C8 (ntdll): (filename not available): RtlLockHeap
00007FF813E436C9 (ntdll): (filename not available): RtlAllocateHeap
00007FF813E4265B (ntdll): (filename not available): RtlAllocateHeap
00007FF7BC792B1C (node): (filename not available): v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
00007FF7BC792B55 (node): (filename not available): v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
00007FF7BBC218CC (node): (filename not available): v8::internal::NativesCollection<2>::GetBuiltinsCount
00007FF7BBC78D73 (node): (filename not available): v8::internal::ParseInfo::parameters_end_pos
00007FF7BBC01B95 (node): (filename not available): v8::internal::OptimizedCompilationInfo::zone
00007FF7BBBFF8F8 (node): (filename not available): v8::internal::OptimizedCompilationInfo::zone
00007FF7BBC028FC (node): (filename not available): v8::internal::OptimizedCompilationInfo::zone
00007FF7BBC74591 (node): (filename not available): v8::internal::ParseInfo::parameters_end_pos
00007FF7BBD5CBC3 (node): (filename not available): uv_tcp_getpeername
00007FF7BBD6E7D7 (node): (filename not available): uv_dlerror
00007FF7BBD13557 (node): (filename not available): node::NewContext
00007FF7BBD13EB3 (node): (filename not available): node::NewIsolate
00007FF7BBD14708 (node): (filename not available): node::Start
00007FF7BBBFEB09 (node): (filename not available): v8::SnapshotCreator::`default constructor closure'
00007FF7BC76EC98 (node): (filename not available): v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
00007FF8112D3034 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FF813EA1431 (ntdll): (filename not available): RtlUserThreadStart```

**Comment by ngokevin** [comment] 2018-09-15 05:31
A-Painter loads for me now at least on Macbook.

**Comment by modulesio** [comment] 2018-09-15 05:34
I could never reproduce this either; it seems windows or env-specific.

**Comment by chrislatorres** [comment] 2019-03-16 00:00
Closing this issue due to being outdated.

**Closed by chrislatorres** 2019-03-16 00:00 UTC
Labels: bug
