### ISSUE TITLE
Pressing a keyboard key after the app opens kills the app. 

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#383] opened 2018-08-28 15:29 UTC
Exokit Version 0.0.420 < - love this version btw! ;)
Windows 10 x64
App: Shane's Editor
```
TypeError: Cannot set property key of #<KeyboardEvent> which has only a getter
    at KeyboardEvent.init (c:\exokit\src\Event.js:117:14)
    at new KeyboardEvent (c:\exokit\src\Event.js:113:34)
    at nativeWindow.setEventHandler (c:\exokit\index.js:479:32)
    at Timeout._recurse [as _onTimeout] (c:\exokit\index.js:1121:18)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Bugsnag:  Encountered an uncaught error, terminating…
TypeError: Cannot set property key of #<KeyboardEvent> which has only a getter
    at KeyboardEvent.init (c:\exokit\src\Event.js:117:14)
    at new KeyboardEvent (c:\exokit\src\Event.js:113:34)
    at nativeWindow.setEventHandler (c:\exokit\index.js:479:32)
    at Timeout._recurse [as _onTimeout] (c:\exokit\index.js:1121:18)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by modulesio** [comment] 2018-08-28 18:47
I don't think there are any [handlers in the Exokit code](https://github.com/webmixedreality/exokit/blob/2ece9a95eeeb683e8618b64c32c0d8093b0526e7/src/Event.js#L117) for `key`, so I'm guessing a `defineProperty` override might be coming from A-Frame.

**Comment by shaneharris** [comment] 2018-08-29 13:02
cool beans, ill do some more invstigating and see if i can nail this down. it might be something im doing.

**Comment by chrislatorres** [comment] 2018-09-02 06:13
I was not able to reproduce the issue on

Exokit Version 0.0.420
Ubuntu 18.04
Shane's Editor ( https://shaneharris.github.io/shanes-editor/ or https://github.com/shaneharris/shanes-editor/tree/d4b8c129f8a8bb8b0e5fbb290770e3197d165f03 )

are there specific repro steps where the keyboard key kills the app?

**Comment by shaneharris** [comment] 2018-09-03 06:26
it was just that, any keyboard input while running shanes-editor in VR. sorry i should have tested this more thoroughly by now but been super swamped. I will have this sorted by the weekend.

**Comment by chrislatorres** [comment] 2019-03-15 22:00
Closing this issue due to being outdated.

**Closed by chrislatorres** 2019-03-15 22:00 UTC
Labels: bug
