### ISSUE TITLE
ML: not sure MutationObserver is working?

### ISSUE THREAD

**Issue by machenmusik** [webmixedreality/exokit#582] opened 2018-11-03 07:38 UTC
Working on a crude alternative implementation for hear what I hear, since ML is deprecating the proper API, I wrote some code based on MutationObserver to run when audio elements are created / attached / detached.  However, that code does not seem to run correctly on ML with Exokit.  (document.body observer...)

**Comment by modulesio** [comment] 2018-11-03 10:04
Can you provide a reproduction? Which part is not correct?

**Comment by modulesio** [comment] 2018-11-24 04:21
Closing this because there are no reproduction steps -- please re-open if there are.

**Closed by modulesio** 2018-11-24 04:21 UTC
