### ISSUE TITLE
MacOS .app bundle is unsigned

### ISSUE THREAD

**Issue by shawwn** [webmixedreality/exokit#55] opened 2018-05-10 00:21 UTC
Downloading from get.webmr.io yields the following error:

![image](https://user-images.githubusercontent.com/59632/39845907-31201462-53be-11e8-8498-d6bbdd93d4e3.png)

**Comment by modulesio** [comment] 2018-05-10 00:58
Is this related to code signing? If so, what happens on a custom generated cert with the same `.travis.yml` steps?

**Comment by modulesio** [comment] 2018-05-10 01:40
Attempted fix in https://github.com/webmixedreality/exokit/commit/1aa018c63c37171faa536f8b781427de40587996

**Comment by modulesio** [comment] 2018-05-10 01:45
The release dropped with this works for me: https://github.com/webmixedreality/exokit/releases/tag/v0.0.248

@shawwn Can you confirm?

**Comment by modulesio** [comment] 2018-05-10 03:37
The bug was an Apple Developer ID certificate was required (we already had one).

Signed the `.dmg` but now the issue is the `.app` + `dylibs` apparently need to be signed as well. Related research: https://successfulsoftware.net/2012/08/30/how-to-sign-your-mac-os-x-app-for-gatekeeper/

**Comment by modulesio** [comment] 2018-05-11 16:42
Decent first pass is in https://github.com/webmixedreality/exokit/pull/58

**Comment by modulesio** [comment] 2018-11-25 02:59
Closing in favor of newer issue https://github.com/webmixedreality/exokit/issues/613.

**Closed by modulesio** 2018-11-25 02:59 UTC
Labels: bug
