### ISSUE TITLE
Support key A-Frame examples with "known good" versions

### ISSUE THREAD

**Issue by kfarr** [webmixedreality/exokit#606] opened 2018-11-21 20:37 UTC
To support developers using A-Frame and Exokit on the Magic Leap, it would be nice to have a few "known good" examples that are regularly updated and serve as key building blocks for most any type of app.

Basic A-Frame example (https://aframe.glitch.me/) currently showing white screen in every direction. I couldn't decipher the hundreds of lines of console log output sorry but it is totally ok to lock support for a specific a-frame version instead of using master and host that demo page yourself, perhaps only updating A-Frame version once it is tested as working. 

Nice to have and almost working great! Superhands laser controls - very useful component for almost any app: https://wmurphyrd.github.io/aframe-super-hands-component/examples/mouse/

This one seems to load but the height of the floor is too high (looks like it's being placed at headset height instead, approx 1.6m too high). The controller maps to support superhands with ML! Funny to see Vive controller there instead but it works well enough.

**Comment by kfarr** [comment] 2018-11-21 20:44
Log of opening http://aframe.glitch.me/
```
11-21 12:42:57.418  3456     4 I exokit  : ---------------------exokit start 1
11-21 12:43:00.180  3456     6 I exokit  : NvRmPrivGetChipIdLimited: Could not read Tegra chip id/rev 
11-21 12:43:00.180  3456     6 I exokit  : Expected on kernels without fuse support, using Tegra K1
11-21 12:43:00.180  3456     6 I exokit  : NvRmPrivGetChipPlatform: Could not read platform information 
11-21 12:43:00.180  3456     6 I exokit  : Expected on kernels without fuse support, using silicon
11-21 12:43:00.815  3456     6 I exokit  : __bionic_open_tzdata_path: ANDROID_DATA not set!
11-21 12:43:00.815  3456     6 I exokit  : __bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
11-21 12:43:00.815  3456     6 I exokit  : __bionic_open_tzdata_path: ANDROID_DATA not set!
11-21 12:43:00.815  3456     6 I exokit  : __bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
11-21 12:43:01.476  3456     5 I exokit  : A-Frame Version: 0.8.2 (Date 2018-04-15, Commit #b20527f)
11-21 12:43:01.476  3456     5 I exokit  : three Version: github:supermedium/three.js#r90fixMTLLoader
11-21 12:43:01.476  3456     5 I exokit  : WebVR Polyfill Version: ^0.10.5
11-21 12:43:01.496  3456     5 I exokit  : THREE.WebGLRenderer 90
11-21 12:43:02.399  3456     5 I exokit  : frameworks/perception/src/perception_context.cpp(272) DoStartup():
11-21 12:43:02.399  3456     5 I exokit  : ALW: [ LLComm ] Obtained frame time handle, using wearable pose timestamps.
11-21 12:43:02.432  3456     5 I exokit  : frameworks/perception/src/trackers/ihead_tracker.cpp(56) IHeadTracker():
11-21 12:43:02.432  3456     5 I exokit  : ALW: reason=idGenerated,source="Head",for=world,id="{3a17569a-ff71-7018-94b2-29841322558d}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=0,id="{06f845ea-400a-7018-adfb-17ac82dbe54d}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=1,id="{b723e4e0-33e4-7018-bb22-27844333541a}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=2,id="{ee94aabf-64b7-7018-9100-651e1f350cd6}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=3,id="{09279fac-3464-7018-b5ff-d5d9ec7a5d88}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=4,id="{42a340d9-1016-7018-be2c-7ecb0f09fb47}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=5,id="{f24a19b2-356a-7018-971f-78a205ca3358}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=6,id="{e89063f4-0105-7018-b0ae-4c635b7a1169}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=7,id="{1e543070-3ac3-7018-baa5-67bc6e343afd}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=8,id="{80907eca-ad12-7018-8d25-9006f4286d11}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=9,id="{f1eb11ce-35fa-7018-859a-3c2a9cec38d0}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.460  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=10,id="{14482ffd-7240-7018-9f32-96d2abb02702}"
11-21 12:43:02.460  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.469  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=42,id="{f02a3fa0-3725-7018-9e94-6f0fdaad646a}"
11-21 12:43:02.469  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.469  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=43,id="{92cc56cc-0e1d-7018-84a5-5fab55c19a14}"
11-21 12:43:02.469  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.469  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=44,id="{78afec9c-20aa-7018-84d4-e549efd8a5c7}"
11-21 12:43:02.469  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.469  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=45,id="{937a3ecf-b8d2-7018-bbbc-e37ae17fc90c}"
11-21 12:43:02.469  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.469  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=46,id="{cb91c84f-4ce0-7018-870c-c4b1a2c43ac8}"
11-21 12:43:02.469  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker.cpp(97) HandTracker():
11-21 12:43:02.469  3456     5 I exokit  : ALW: reason=idGenerated,source="HandTracking",hand_tracking_pose=47,id="{24a36387-bd79-7018-a1d0-f43b99f630f9}"
11-21 12:43:02.577  3456     5 I exokit  : frameworks/perception/src/perception_context.cpp(789) SetRigTransforms():
11-21 12:43:02.577  3456     5 I exokit  : ALW: Setting new rig transforms in perception_context
11-21 12:43:02.577  3456     5 I exokit  : frameworks/perception/src/trackers/calibration.cpp(990) Update():
11-21 12:43:02.577  3456     5 I exokit  : ALW: reason=processedUpdatedRigModel,timestamp=3123776269000
11-21 12:43:02.577  3456     5 I exokit  : frameworks/libs/llcommcpp/llcomm_helpers/impl/llcomm_helpers.cpp(252) SafeQueryByTime():
11-21 12:43:02.578  3456     5 I exokit  : ERR: reason=llcomQueryError,handle_name=gesture_llcomm,time_us=18446744073709551615,status=23=LLCOMM_PERMISSION_DENIED
11-21 12:43:02.578  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker_llcomm.cpp(194) Update():
11-21 12:43:02.578  3456     5 I exokit  : ERR: [ LLComm ] Failed to complete query for [ gesture_llcomm ].
11-21 12:43:04.006  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:04.065  3456     5 I exokit  : frameworks/perception/src/trackers/hand_tracker_llcomm.cpp(197) Update():
11-21 12:43:04.065  3456     5 I exokit  : ALW: [ LLComm ] Successfully queried for [ gesture_llcomm ].
11-21 12:43:09.091  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:09.346  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:09.601  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:09.856  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:10.111  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:10.367  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:10.622  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:10.878  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:11.133  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:11.388  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:11.643  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:11.898  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:12.154  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:12.410  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:12.665  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:12.921  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:13.177  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:13.432  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:13.687  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:13.943  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:14.199  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:14.453  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:14.709  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:14.966  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:15.220  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:15.475  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:15.730  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:15.985  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:16.241  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:16.415  3456     5 I exokit  : malleus/ml_binder/calibration/calibration_sub_client_binder.cpp(64) onRigModel():
11-21 12:43:16.415  3456     5 I exokit  : ALW: onRigModel got rig model buffer of size 503895
11-21 12:43:16.496  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:16.756  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:17.011  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
11-21 12:43:17.266  3453     1 E NoTag   : MLGraphicsBeginFrame complained: 2
```

**Comment by modulesio** [comment] 2018-11-21 20:45
Re: the floor thing, that sounds like https://github.com/webmixedreality/exokit/issues/351.

**Comment by kfarr** [comment] 2018-11-21 20:51
Yes all of this relates to #351. A-Frame demo working fine, just too high to see the models (and the scene has opaque white sky) so it all appears white.

**Comment by modulesio** [comment] 2018-11-23 03:19
I'll close this as a dupe of https://github.com/webmixedreality/exokit/issues/351.

Having a solid list of examples _is_ a great feature request and something that's in the works, but it seems the issue here was a missing frame of reference implementation.

**Closed by modulesio** 2018-11-23 03:19 UTC
Labels: duplicate
